### ISSUE TITLE
Visual Bug: Explore filter on mobile

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1152]
The explore filter needs a mobile overhaul.

@meiqimichelle do you remember which issue has @ericronne 's mocks for this section?

**Comment by ericronne** [comment]
@gemfarmer The pertinent issue is loaded with images; for simplicity's sake, here you go. LMK if you have q's / comments! NOTE: filter button bar is meant to be sticky....

### Default ###
![explore-jobs-default](https://cloud.githubusercontent.com/assets/9259185/12153629/7e29eb32-b480-11e5-8f7e-95d645465f2e.png)

### Filter opened ###
![explore - jobs - filter - opened](https://cloud.githubusercontent.com/assets/9259185/12153628/7e2968ce-b480-11e5-9307-61d12dac576b.png)

### Sketch file ###
https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaeFpBMElVdEJHTTg/view?usp=sharing

**Comment by ericronne** [comment]
@gemfarmer it might be good for us to do a hangout before digging into changes to this in earnest, but here are a few of the issues i'm noticing on iphone 6 (may already be known)...
 - [ ] Sticky filter button / title ("sticky unit"!) jumps to the top when scrolling, rather than sticking when it hits the top
 - [ ] Sticky unit should be pushed upwards by the top of the footer (currently vanishes, then reappears near the bottom of the screen before eventually scrolling away)
 - [ ] Sticky unit is too narrow (leaves a gap on the right)
 - [ ] The chart title should always appear below the filter button, as it does when the filter is expanded
 - [ ] The page scrolls to the top when any filter selector is tapped
 - [ ] To increase legibility, we may need to make the blue panel 10% or so less transparent, and also change the selector headers to Regular instead of Light
 - [ ] The down arrows on the selectors look a little fuzzy and black, and the labels are black and appear to be the wrong font (sb lato reg #115F83)

**Comment by meiqimichelle** [comment]
After our restructuring of the 'explore data' section, the only page that has this interaction still is the [federal revenue by company](https://useiti.doi.gov/explore/federal-revenue-by-company/2015/#) page. Leaving this open, but not not actively working on this now until we decide if that interaction remains the same.

**Comment by coreycaitlin** [comment]
Here's the updated link for where to find this filter: [federal revenue by company](https://useiti.doi.gov/how-it-works/federal-revenue-by-company/2015/)

**Comment by gemfarmer** [comment]
This is for the v1 of the site. Closing
