### ISSUE TITLE
Visual bugs: misc desktop

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#1204]
### Global
A few tweaks to this collection of utilities...
![image](https://cloud.githubusercontent.com/assets/9259185/12248096/c938019a-b87c-11e5-893e-aff397fbc0de.png)
 - [x] "Glossary | Downloads" should move up two pixels, to vertically align with the word "Search"
 - [x] Vertical bar dividing glossary and downloads should be light gray
 - [x] Search box should be one pixel taller, so the outline aligns with the blue mag-glass button
 - [ ] I hear a rumor that it's difficult to play with the spacing between link text and underscores which appear on hover. True? ;) If not, let's chat! __holding off on this on for now. See comments below__

### Home
 - [ ] Blue "water" in "See how it works" teaser should move down to align with the bottom of the wide blue areas, so that no light blue shows below it __moved to__ #1243

**Comment by gemfarmer** [comment]
@ericronne it isn't super tricky to play with the spacing between text and underscores, but definitely not preferable, as we would be messing with the default functionality. Let me know if you still want to try to play with this.

**Comment by meiqimichelle** [comment]
Well, tricky to make it look the same across browsers @gemfarmer unless you know something I don't. And then if you take out `text-underline` and use borders instead there's all sorts of other things to be worked out -- like hacks to make that work for underlines that cross a line break, for example. But, entirely possible that you know a solution that I do not.

**Comment by gemfarmer** [comment]
@meiqimichelle in my comment I was assuming it would mean using border-bottoms to manipulate spacing between text, which I didn't think had any sort of cross-browser issues. Do they?

Either way, I would prefer to stick to the default if it isn't essential.

**Comment by meiqimichelle** [comment]
They have minor cross-browser issues -- similar to how that search box on the upper right was a jerk to get lined up exactly the same across browsers because each one calculates pixel rounding slightly differently. So, you're trying to get like a light, one-pixel border exactly the same and it comes out slightly darker/lighter/higher/lower depending on the browser. That, plus the multi-line thing. <-- big jerk, that problem.

We'd have to implement something like this: https://eager.io/blog/smarter-link-underlines/
And then go through the entire site to make sure it implements correctly in all cases and on all background colors. So, do-able, but not trivial.

**Comment by ericronne** [comment]
Thanks! Very educational.
To backlog, Batman! :D

**Comment by gemfarmer** [comment]
All tasks have been either met or moved to different issues.
