### ISSUE TITLE
Explore > Reconciliation: Explain material variances

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1233]
On the reconciliation page, it would be great to be able to click on each red number and see the explanation for that variance.

**Comment by meiqimichelle** [comment]
Also, we should change the red to bold (or another indication of special-ness).

@coreycaitlin , @splatts -- do we have a list of the explanations for the variances somewhere?

**Comment by splatts** [comment]
@meiqimichelle @coreycaitlin I sent Corey the appendix, which our Reconciliation team mentioned had the explanation of variances. @coreycaitlin did that give you what you needed? I know we discussed last week, so lmk if you need anything else!

**Comment by coreycaitlin** [comment]
Yep, I've got that document — just need to work through it and pull out (and possibly edit?) the explanations.

**Comment by coreycaitlin** [comment]
Now working through the explanations to come up with more concise versions of each.

Quite a few of the explanations are variations on the following type:

> $54,318,974 was reported by Chevron Corporation as paid in December 2012 but was recorded by ONRR in 2013.

Does that phrasing seem accurate, @splatts?

**Comment by usEITI** [comment]
Correct.  We chose as an MSG to report on a calendar year basis.  When a
company submits a payment, there is a brief lag time when the ONRR system
records the payment as received. Hence the December / January timing
discrepancy.

On Mon, Feb 1, 2016 at 8:20 PM, Corey Mahoney <notifications@github.com>
wrote:

> Now working through the explanations to come up with more concise versions
> of each.
>
> Quite a few of the explanations are variations on the following type:
>
> $54,318,974 was reported by Chevron Corporation as paid in December 2012
> but was recorded by ONRR in 2013.
>
> Does that phrasing seem accurate, @splatts <https://github.com/splatts>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/issues/1233#issuecomment-178293473>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by gemfarmer** [comment]
@coreycaitlin I just merged a branch with dummy footnotes added. Tge references are generated, so you only need to worry about the footnote text :)

**Comment by meiqimichelle** [comment]
From our latest round of [usability testing](https://github.com/18F/doi-extractives-data/blob/research/research/sprint-splashysunfish/sprint-splashysunfish_results.md):

### Do people understand that the variances were all explained?

**Nope nope nope, not yet.** People reacted very strongly to the companies who had highlighted material variance numbers, even after we changed the color from red to bold. Note: we don't have footnote text done yet that explains the variances. Maybe this will help, but I expect that we're going to more than just those notes because participants had strong assumptions about this part of the data. For example, they assumed that if the gov and company numbers differed, it was because a company had been 'bad' and they needed to pay the government, when really we're just talking about discrepancies in accounting.

- _[Gets to a company that has a red number] Chevron! Tsk tsk. Apparently only Chevron sucks. Ooooo. [Continues scrolling, finds more red] 220% difference?! You guys need to pay up!_

- _Chevron! OOOOO! Now we’re getting to the good stuff. Pay it, Chevron! [continues looking through data] Exxon, jeez louise! [laughing]_

- _In looking down the list, I see that most of the time, there’s not a problem. But sometimes there’s a big gap, and I want to find those. [Participant wanted a way to filter to the 'problem' companies]_

Only one participant noticed that one of the discrepancies included a negative number, and so mused about that, yet still wasn't able to feel confident in what was going on.

- _Oh -- hold on -- here’s one that’s like 50% off, but it’s negative [The company side shows in parentheses]. Huh. [thinking] So this must mean that it’s not always the company that owes money to the government? Wha -- so the, um, government has to pay them back? I’m not sure about that._

It seemed like even though people seemed to understand the words "material variance" when they read it in the intro paragraph and clicked on the glossary definition, the use of that concept in the summary chart and company listings is one mental leap too far; we're not connecting the dots enough for folks. In particular, our attempt to use material variance in the summary chart was not well understood.

- _Not knowing anything about this -- [I go through the page and see] oh, something material, something is bolded, that’s what is important and what I should look at._

- _Kinda the meta question is -- these material variances -- should I think of that as an ethical question? Am I supposed to think this is this sloppy bookkeeping? Citizenship-wise, I don't see what I should make of these big variances._

**Comment by meiqimichelle** [comment]
@coreycaitlin Should we close this one?

**Comment by meiqimichelle** [comment]
We implemented a change, but we still need to test it.

**Comment by meiqimichelle** [comment]
We are pausing work on the reconciliation page as per @usEITI in favor of the state/tribal dashboard work that ranks highly in user need, stakeholder preferences, and requirements for international EITI. Moving this to the backlog.

**Comment by coreycaitlin** [comment]
I believe we have finally solved this by including the words "fully explained" in every footnote, as well as including the flowchart above.
