### ISSUE TITLE
Coal Excise Tax Visualization

### ISSUE THREAD

**Issue by splatts** [18F/doi-extractives-data#1280]
@meiqimichelle @coreycaitlin cc @Isabelle1512 The second part of our first visualization update for Contextual is Coal Excise Tax. This one is a bit more straight forward than AML, as we have received guidance to address it as an additional revenue stream and provide an overview of the program itself. 

As you can see in this one, we had some hypotheses on where we could include this in the current site's info architecture. Would love your guys' thoughts as well! And, like AML, we'll also be collecting feedback so will have an updated wireframe next week.

[2016Feb15_Coal Excise DRAFT Mock Up_v1.pptx](https://github.com/18F/doi-extractives-data/files/134886/2016Feb15_Coal.Excise.DRAFT.Mock.Up_v1.pptx)

**Comment by coreycaitlin** [comment]
I've pulled this content into the site structure under How it Works, and brought it all into Markdown with footnotes. 🐰  [PREVIEW HERE](https://federalist.18f.gov/preview/18F/doi-extractives-data/coal-excise-content/how-it-works/coal-excise-taxes/) 🐰 

A few notes:

- I think it's worth having this as a separate page in How it Works, because we aren't really able to include images within steps inside of the diving graphics (aka How it Works > Coal). We can add a simple mention and hyperlink in the Coal diving graphic to connect people to this page.
- I didn't create a right-hand nav for this page, because I think it's concise enough that it doesn't really need one.

I've included a screenshot of the revenues trend graph as a placeholder. @ericronne, we may need your help to make this match similar graphs on the site.

**Comment by coreycaitlin** [comment]
Next steps:

- Add coal excise rates to How it works > Revenues chart of revenue rates
- Link from How it works > Revenues page
- Make sure it's clear that both Coal Excise Taxes and AML fees are paid on ALL lands, not just federal lands

Does that cover it @avarnum?

**Comment by avarnum** [comment]
Hi @coreycaitlin, thanks for capturing these notes. Definitely those things and a few more to add: 

1. Let's make sure the title is Coal Excise Tax (not "taxes)
2. Please add the "For more information" text box to the Coal Excise page. This links to public information on the Black Lung Disability Program and Trust Fund

Thanks very much!

**Comment by coreycaitlin** [comment]
Closing this out, since we've incorporated all feedback so far. We'll open up a new one if we get further notes.
