### ISSUE TITLE
Adjust design on case studies page

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1282]
People aren't seeing the dropdown on the case studies page. ie, they don't know what there are 12 case studies and that they can navigate between them.

**Comment by ericronne** [comment]
- [ ] Flop the position of the map and the " Choose a community..." selector
 - [ ] Left-align the selector with the right-side nav ("Top" etc.)
 - [ ] Make the selector sticky
 - [ ] Make the selector narrower (let's talk if this is an issue!)

### before scrolling…
![image](https://cloud.githubusercontent.com/assets/9259185/13153028/a058b570-d637-11e5-9cc6-9c65b310944d.png)

### scrolled…
![image](https://cloud.githubusercontent.com/assets/9259185/13153083/e005a69c-d637-11e5-9878-7d03f6b678f0.png)

**Comment by meiqimichelle** [comment]
Note: while we're there, take a look at the what's clickable on the menu -- right now the entire area is hover-able, but it should probably be just the word.

**Comment by ericronne** [comment]
I don't want to make this into a "meta task," but the natural resources and laws and governance sections and these pages would ideally match up stylistically. Currently we use selectors on those pages to jump to different sections of the page, but here we have the stacked nav which is always visible, and the selector gets you to a different page.

I like the case studies paradigm:
 - Selector to choose a different page in the section
 - Stacked text options to jump around the page you're on

Since the nav is sticky, this approach could be an issue if we had too many sub-sections on a page. The only place i see this as a potential danger is on the [regulations in 18 states page] (https://useiti.doi.gov/how-it-works/state-legal-fiscal-info/). Would the nav simply get a scroll bar in this case, if the user had a small monitor?

We could split the nav into two columns no that page, mayhaps…
![image](https://cloud.githubusercontent.com/assets/9259185/13178827/a16fa4a0-d6e6-11e5-94cb-86c5d53de38c.png)

**Comment by meiqimichelle** [comment]
Once we have 'regional pages', I'm not sure we still will have this separate regulations page. It feels like something that should be revealed on the regional view that we're talking about in #1267 . BUT! Hmm. Maybe there's something here that serves the 'national overview' view that we're talking about preserving, with a click-through to a regional page???

I see what you're saying about matching the styles tho. I wonder if there's more thought there to be had around our 'landing' pages generally -- since people aren't scrolling on them, and not finding all the info anyways.

**Comment by ericronne** [comment]
Most of the other how-it-works subs which have that selector would still exist, i think. That's the only one with a state pulldown.

And yep the lack of a persistent sub-subnav makes it difficult to keep track of your location and zip around between those sub pp. Is there an issue for this?

**Comment by ericronne** [comment]
There is now: #1286

**Comment by meiqimichelle** [comment]
DOn't implement this change yet. According to @ericronne , perhaps the changes in #1286 or similar might better fix the issue (ie, deal with global subnav first).

**Comment by meiqimichelle** [comment]
This work is continued in #1632. Closing.
