### ISSUE TITLE
Add solar and wind info to revenue process chart

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1558]
This is a remaining piece of #1459. Corey's content from that issue has been implemented, except for the info on solar and wind revenues. We need this.

**Comment by gemfarmer** [comment]
Q: Do we have revenue by type data for solar and wind?

**Comment by gemfarmer** [comment]
@coreycaitlin and I are going to find time to pair on this.

**Comment by coreycaitlin** [comment]
It looks like we have federal revenue info for offshore wind energy production in federal waters in the Atlantic Ocean, but no data for federal revenue from onshore wind or solar energy production on federal lands. This may be because those revenues are handled by BLM instead of ONRR (according to [How it works > Renewables](https://useiti.doi.gov/how-it-works/onshore-renewables/)).

For now, the simplest next step might be to note these types of revenue in the "Other revenue" section below the table.

**Comment by coreycaitlin** [comment]
- [ ] fix hardrock mining links
- [ ] onshore renewables
- [ ] link to federal revenue by company
- [ ] offshore wind when there's offshore wind data

**Comment by coreycaitlin** [comment]
I think #1944 solves this!
