### ISSUE TITLE
Content: Pull in AML visualization content

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#1571]
Pull content from the IA's AML fees visualization into a Markdown page.

**Comment by coreycaitlin** [comment]
🐤  [PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/how-it-works-ia/how-it-works/aml-fees/) 🐤 

All the content should be here, though it could use a review from @avarnum or Luke (whose github name I can't find) to make sure nothing got lost in the Mac scrambling of the PDF interactions.

Next step is to work in feedback, links, and images!

**Comment by avarnum** [comment]
Hi Corey, Michelle, I spoke to Luke and we had a few comments to relay on this one. The overarching feedback is that it looks good, but we need to be really careful of what we change since every word and placement was scrutinized by all the sectors. 

To that end, see below for some edits. You can reach out to Luke with questions while I'm out: 

1. Please inset the 9.2 billion in fees and 1.5 billion in interest back in a call out box from the first page of the PDF. the sectors wanted to make sure that it was repeated up front too. 

2. Please include back the text "The government rates abandoned mine areas on a priority scale of 1–3, as defined by the law:" you can then move the other sentence mines rated 1 and 2 are high priority and should be addressed first, with a few exceptions.1" to after the scale definitions if you think it fits better after than before. 

3. On page 2 of the PDF there is text "to the right" however on the website the statistics referenced are below, please update accordingly. 

I will connect Luke with Corey to provide any additional feedback on the content and to review the visualizations. 

Thanks!
Andrew

**Comment by coreycaitlin** [comment]
Thanks for spotting these — I think we've got all three covered in the `aml-images` branch!

**Comment by coreycaitlin** [comment]
Closing this out — we're going to create a new issue for implementing additional feedback and revisions.
