### ISSUE TITLE
Locale currency support

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#1590]
Javascript supports locale currencies! Let's add them to the site so that other countries can view our project more seamlessly!

Refs:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

![pasted image at 2016_07_11 12_51 pm](https://pbs.twimg.com/media/CmoKS0JVUAA8sEI.jpg)

**Comment by gemfarmer** [comment]
A corollary to this – we might also consider allowing people to convert units to something more accessible/relatable. It might be nice to allow people to convert say `short tons` to `tons`, `kilos`, `lbs`, etc.

**Comment by dmsnell** [comment]
@gemfarmer it's worth noting that all this does is replace the number format and the currency symbol. It does not, for instance, convert the _value_ of the currencies. That is to say that if we give it $100 and ask for JPY it will give us 100¥ (or 百円 maybe) instead of something like 10,000¥ as is the exchange value.

We _could_ hook this up to some API to convert the values, but I imagine that most values here will be historical and the exchange rates fluctuate with time, so some decisions would need to be made on how to make that historical conversion too.

At this point, short of hard-coding the properly-converted values into a variety of currencies in the data itself, is it feasible/practical to enhance the site in this way?

**Comment by meiqimichelle** [comment]
We probably don't need to do this, not a strong user need :) It is cool though! Closing for now.
