### ISSUE TITLE
State pages: connecting a county in drop-down list to map

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1695]
Some users know a county name, some know its location. We should have a design for connecting a name on a county expanda-list to the map, and maybe the converse (perhaps a tool-tip with revenue info on click or hover?)

![screenshot 2016-08-01 10 37 14](https://cloud.githubusercontent.com/assets/4827522/17303072/ee7f4be2-57d3-11e6-8f68-e9ce0b3d39aa.png)

**Comment by gemfarmer** [comment]
_ideas_
**Map --> Chart**: click on map and the table opens with that county's row bolded?
**Chart --> Map**: We probably don't want to change the county's fill color (because then it wouldn't correspond to the legend), but maybe we could change it's stroke color and have a tooltip with name and corresponding data as @meiqimichelle suggested.

**Comment by ericronne** [comment]
+1 re outlining vs altering the county's color on hover, and to your suggestion for behavior. 

### That's what i've done in the [invision prototype here, which y'all should test and comment upon!] (https://invis.io/DP874D145#/179355225_Production_-_Default). ###

 I think a traditional tool tip might be the best route to take for the hover, because it works well for both vertical and horizontal maps.

My topline thoughts re behavior:

 - Hover outlines county with a **two-pixel rule** `#587F4C` bar-chart green **at 50% opacity** and shows tool tip with sentence-style county data:
![image](https://cloud.githubusercontent.com/assets/9259185/17449910/58f07870-5b12-11e6-9b02-48f71069b1ec.png)

 - County click darkens its green outline to full opacity, opens the table (assuming it isn't already open), expands that county's row, adds the sentence-style data, and fills the background of that row with `#F7F7F7`, our $light-gray (an accordion, basically)
![image](https://cloud.githubusercontent.com/assets/9259185/17450067/15805046-5b13-11e6-8168-cfd03e0df680.png)

Again, please leave comments in invision, and we can chat, as well.
Thx!

**Comment by ericronne** [comment]
I removed the green and boldfacing from the table design; i don't think we need it there. On the bars, the green is meant to reinforce the connection between the figure and the selected (green) bar, since they're not adjacent. But here, everything is boxed together ...

![image](https://cloud.githubusercontent.com/assets/9259185/17486262/0b93b634-5d45-11e6-91bb-2249989e6737.png)

**Comment by coreycaitlin** [comment]
I like this a lot, @ericronne — seems super clear to me.

**Comment by gemfarmer** [comment]
@ericronne me too. I'm going to start working on it!

**Comment by gemfarmer** [comment]
Thought for myself for overlapping county SVGs: To highlight a county with no overlap, make a copy of the county mesh and add it to a <g> that sits on top of the state county mesh. When no county is highlighted, this <g> should be empty so that the color neutral, pixel consistent mesh is the top layer.

**Comment by gemfarmer** [comment]
Remaining tasks:
- [ ] update html for all instances of county chart
  - [ ] federal production
  - [ ] revenue
  - [ ] jobs
- [ ] make sentence values update as year changes
- [ ] overlay selected counties svg on top of all county meshes

**Comment by gemfarmer** [comment]
Closing. Spillover issue at #1747
