### ISSUE TITLE
Update How It Works/Revenues with Coal Excise Tax Revenues

### ISSUE THREAD

**Issue by avarnum** [18F/doi-extractives-data#1754]
@meiqimichelle @coreycaitlin 

We have noticed a few modifications that need to be made on the How-it-Works/Revenues Page. 

Specifically, we need to add Coal Excise Tax to the "Select Federal Revenue Streams" table.  

- In the Surface Mining row in the During Production column: "$0.55 per ton or 4.4% of the sales price (whichever is lower) coal excise tax"
- In the Subsurface Mining row in the During Production column: "$1.10 per ton or 4.4% of the sales price (whichever is lower) coal excise tax"

See screenshot attached for location and please let us know if you have any questions. 

![coal excise tax additional information](https://cloud.githubusercontent.com/assets/20306455/17746593/b152671a-647e-11e6-98e1-cdaf4123b3ac.JPG)

We also need to cut the word "DOI" from the top of that chart as Coal Excise Tax Revenues are not collected by DOI.

**Comment by avarnum** [comment]
tagging @lukehawbaker

**Comment by meiqimichelle** [comment]
Coal Excise Tax isn't a DOI revenue so it doesn't really fit in this chart. We might consider adding a separate sentence, or something that links to the info.

**Comment by lukehawbaker** [comment]
@meiqimichelle yep! our thought had been to remove DOI from the top of the chart (see Andrew's comment at the bottom)

**Comment by coreycaitlin** [comment]
Because this chart was originally limited to revenue streams that were *both* classified as "in-scope" by the MSG *and* collected by DOI, we want to keep things that don't meet both of those criteria on other parts of the page (in part because this chart will get impossibly teensy and hard to read if we try to fit too much in).

I think we've resolved the core issue here by linking to the coal excise page in the "Other taxes and fees" section:
![screen shot 2016-09-14 at 3 40 56 pm](https://cloud.githubusercontent.com/assets/1450354/18532558/ab46c1c6-7a91-11e6-89f4-70866c78e632.png)
