### ISSUE TITLE
Bug: Alaska revenue county table is splitting by commodity

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#1946]
We've got lots o North Slopes happening here :) Should be one value.
![screenshot 2016-09-15 08 31 01](https://cloud.githubusercontent.com/assets/4827522/18556108/2ef25fac-7b1f-11e6-9cfb-bc90d5eb199a.png)

**Comment by gemfarmer** [comment]
@mentastc @mhz @shawnallen Unfortunately, this is weirder than I was expecting.  The issue is actually consistent with both the outputted data _and_ the source data. For revenue data, North Slope has several different FIPS codes and corresponds to the FIPS and borough Bristol Bay. Quite bizarre. The question, it seems to me, is whether or not we want to roll all of the fips associated with North Slope into one data point, or whether or not we want to specify them individually, like we are doing now. 

I am leaning towards the first option, because not all of the FIPS codes used for north slope have corresponding svg paths, so we would only have to worry about this on the data side of things.

**Comment by gemfarmer** [comment]
Source data: https://raw.githubusercontent.com/18F/doi-extractives-data/dev/data/revenue/onshore.tsv

Outputted data: https://github.com/18F/doi-extractives-data/blob/dev/_data/county_revenue/AK.yml
