### ISSUE TITLE
Add pop-out functionality to ownership maps

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2071]
It might be handy if users could click on state ownership maps to open a larger version in a new window.

cc @meiqimichelle @gemfarmer

**Comment by gemfarmer** [comment]
Oo interesting. Definitely an enhancement, but a cool one

**Comment by coreycaitlin** [comment]
Interesting — I'd want to validate that this was useful to users before going too far down the implementation path, though. At one point, a few users were getting confused by _overemphasis_ of the ownership concept, which led us to change/clarify the hierarchy of the state profile pages.

One option for folks who want to know more about land ownership in general is to link to the source data instead, since that would also have more nuanced context, especially about tribal land.

**Comment by ericronne** [comment]
So ... await validation via testing!

**Comment by coreycaitlin** [comment]
Closing this issue out — not a priority for the product vision right now.
