### ISSUE TITLE
Collapsible bar charts on mobile!

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2085]
Currently the mobile state pages are looooooooong, particularly sections containing bar charts. Eg ...

![image](https://cloud.githubusercontent.com/assets/9259185/19403770/f19d1684-922e-11e6-9a28-5d2e676e32d2.png)

I think users might find these sections more digestible if we formatted them as accordions, with **sparkbars** (what?! yes!) added to the collapsed state, to give a scannable snapshot of the data shapes ...

![image](https://cloud.githubusercontent.com/assets/9259185/19403814/4aefa288-922f-11e6-8ccf-aa1d82b96043.png)

Expanded bars could look like this ...

![image](https://cloud.githubusercontent.com/assets/9259185/19403834/67346fa0-922f-11e6-8efd-3e2c7f63f9d7.png)

I've broached this to @gemfarmer, who is head over heels in <3 with it (at least that's my take). @coreycaitlin @meiqimichelle @shawnbot 

[**Sketch file**](https://drive.google.com/open?id=0BwWYNZcEDfwaSklhUXF5Yndudjg)

**Comment by gemfarmer** [comment]
remaining to-do list:
- [ ] return to top should go to top
- [ ] sticky navigation bugs
- [ ] add collapsible header to state and offshore pages
- [ ] refine load time for collapsible headers
- [ ] disable clicking on the US explore map on mobile
- [ ] make sure that years changing is reflected in small icon bar charts
- [ ] disbursements table look/feel
- [ ] megachart: 
    - [ ] fix tabs overlapping/stacking issue
    - [ ] fix header sizing
- [ ] mobile sticky nav should say “Nationwide data” instead of Explore Data
- [ ] icons: +/- on collapsing charts, under maps
- [ ] Potentially collapsible megachart and disbursements chart

cc @ericronne

**Comment by ericronne** [comment]
done!
