### ISSUE TITLE
Negative bar chart values

### ISSUE THREAD

**Issue by gemfarmer** [18F/doi-extractives-data#2167]
## Expected Behavior
Negative values should look different than positive values

## Actual Behavior
<img width="300" alt="screen shot 2016-11-29 at 12 23 47 pm" src="https://cloud.githubusercontent.com/assets/4803473/20723091/ba9b7198-b62e-11e6-80c3-450e5b923ddb.png">

https://twitter.com/ed_reed/status/798957802492461059

## Steps to reproduce the behavior
?? This would totally screw with our bars :(

cc @ericronne

**Comment by ericronne** [comment]
I would consider changing both the amount and the year to red, and show no bar at all.

**Comment by gemfarmer** [comment]
That would definitely be easier to pull off. Is red going to be frowned on in this case?

**Comment by ericronne** [comment]
I would think it might be okay, since it's used that way in annual reports, etc.

Almost feel like the sentence should be rewritten. :/

@coreycaitlin @meiqimichelle 👋

**Comment by ericronne** [comment]
@coreycaitlin bump! ;)

**Comment by coreycaitlin** [comment]
This will definitely take pairing time @gemfarmer — the sentence will have to be different enough for negatives that we'll need to wrap the whole sentence in an if statement to figure out if the number is negative, and I'm not sure how!

**Comment by gemfarmer** [comment]
@coreycaitlin ok! I can take a look to see how realistic this solution is given the constraints you are bringing up. If it is reasonable, we get set aside some pairing time. Not sure how high a priority this is though!

**Comment by coreycaitlin** [comment]
`In [YEAR], helium production on federal land yielded [-#] in federal revenue.`

But we probably need an explanation of how this can happen somewhere...

**Comment by jeremiak** [comment]
Did some investigating with @master12 and we think we have three options. In this example, we are looking at helium for the country and using 2017 as the selected year since the value is negative.

Here is the chart with red numbers to indicate negative numbers (with no bars):
<img width="242" alt="screen shot 2018-03-27 at 12 19 34 pm" src="https://user-images.githubusercontent.com/780941/37980455-2e5f7b86-31b9-11e8-94d2-574dcc856133.png">

Here is the chart where we have reset the scale so that the bottom is always 0. You can still see some of the years that have negative values in this example but they wouldn't be there in the implementation:
<img width="255" alt="screen shot 2018-03-27 at 12 21 15 pm" src="https://user-images.githubusercontent.com/780941/37980554-61040d90-31b9-11e8-887d-e95a8b534d27.png">

We could do a third option which would be to have a floating X axis in the chart that represents 0 and have bars go up or down from that. It potentially makes the charts even harder to scan next to each other since the placement of that axis might change.

In any event, we should also rework the sentence since a company "paying" a negative amount is weird. I'm still a little bit unclear on the dynamic that leads to a negative value so I'll leave the copy decision to @brentryanjohnson.

**Comment by brentryanjohnson** [comment]
FYI...here is a floating chart example.

![floating chart example](https://user-images.githubusercontent.com/32855580/37983747-24bc0136-31a9-11e8-9c3c-05769ce489b2.png)

**Comment by master12** [comment]
First design step will be to set the min value to 0 and change the font to red for negative years

**Comment by brentryanjohnson** [comment]
Let's rewrite the sentence based on conditional logic denoting a negative value. Here are some options:

## Draft options

- [ ] ONRR adjusted revenue for the production of `commodity` on federal land by `-$value` in `year`.
- [ ] Overpayment for the production of `commodity` on federal land led to an adjustment of `-$value` in `year`.
- [ ] Revenue for the production of `commodity` on federal land was adjusted by `-$value` in `year`.
- [ ] Revenue for `commodity` was adjusted by `-$value` in `year`. This is usually because of overpayment in a previous year.
- [ ] In `year`, `commodity` production on federal land yielded `-$value` in federal revenue.

## Examples

![revenue prototype one](https://user-images.githubusercontent.com/32855580/37986378-24e95314-31b0-11e8-85c7-8b2c83cbad6c.png)

![revenue prototype two](https://user-images.githubusercontent.com/32855580/37986247-cea6dd32-31af-11e8-9018-5aa91e1035f8.png)

**Comment by jennmalcolm** [comment]
There are some good options here. To keep things straightforward and with less built in interpretation, I would stay away from saying that revenues were adjusted by that amount because revenues could have been adjusted by more than the negative amount. I most prefer number 5, but believe that the explanation in number four could be added on to explain. So, what about this?

 In accounting year, commodity production on federal land yielded -$value in federal revenue.  A negative revenue number is usually because of over payment in a previous year.

**Comment by brentryanjohnson** [comment]
Thank you, @jennmalcolm.

We have limited space for these captions, so we may need to continue to work on it and see if we can edit it down a bit. Otherwise it breaks our layout to accommodate the additional text. 

I'll see if I can but it down a bit and still retain meaning and context.

![broken template due to amount of caption text](https://user-images.githubusercontent.com/32855580/37990165-4e3a149c-31ba-11e8-977c-c47606053fb0.png)

**Comment by master12** [comment]
code is merged
