### ISSUE TITLE
Google analytics: implement codes for accurate reporting

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2308]
It seems that tracking codes were never added to our site …
![image](https://cloud.githubusercontent.com/assets/9259185/26657156/e49e963a-4627-11e7-86b1-073720683106.png)

Here are the codes assigned by the Goog …
![image](https://cloud.githubusercontent.com/assets/9259185/26657187/ffd437b6-4627-11e7-9d03-4f753d30a9d7.png)

**Comment by coreycaitlin** [comment]
from #2362:

I wanted to increase our ability to understand user behavior by installing GTM (also works with the Digital Analytics Program (DAP))

Copy the code below and paste it onto every page of your website.
Paste this code as high in the of the page as possible:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','GTM-NCRF98R');</script>
Additionally, paste this code immediately after the opening tag:

<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NCRF98R" height="0" width="0" style="display:none;visibility:hidden"></iframe>

**Comment by toolness** [comment]
Hmm, I've been doing some investigation into this and learned a few things:

1. The existing logic for including GA was added in #1351, I think.
2. Looking at the HTML source for https://useiti.doi.gov/ (using my browser's "View source" functionality), there does not currently appear to be any GA tracking code in it. Which I think means that the logic for including GA is not being triggered.

I will try to figure out more and post more details soon.

**Comment by toolness** [comment]
Oh hey, I believe I just fixed this.

In the description for #1351 it was mentioned that Federalist should add the following to our site's configuration:

```yaml
google_analytics:
  default: false
  master: 'UA-48605964-8'
```

However, I looked in our Federalist settings, and this is actually not the case! At some point, someone removed this special configuration data. I just re-added it and re-built the site, and the HTML source of  https://useiti.doi.gov/ now contains the proper GA tracking script code and the correct tracking ID, `UA-48605964-8`!  Huzzah!

The data should start showing up in GA in the next few days I guess.  @ericronne, can you check on the GA site in a bit to see if it's still complaining about that stuff?

BTW, I think it's appropriate to re-open #2362 rather than fold it into this issue, as it's a separate technical concern.  This issue involves fixing EITI's Federalist configuration so GA works again, while #2362 involves adding new code to EITI.

**Comment by toolness** [comment]
Woot, it's working now!

![2017-09-15_12-28-25](https://user-images.githubusercontent.com/124687/30493245-689ea096-9a11-11e7-8401-debc8e15b9c1.png)

Gonna close this issue, and re-open #2362.
