### ISSUE TITLE
Content: Forestry information

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2313]
The IA has gathered significant contextual content about forestry. This will need to find a home on the website, either in the "How it works" section or within "Explore data."

**Comment by coreycaitlin** [comment]
**[DRAFT content here](https://drive.google.com/open?id=0B-tWFsKyyEsKTENXeHJORl9jbVk)**

Noting that this is blocked until the content is finalized.

**Comment by coreycaitlin** [comment]
Now unblocked — content is final and ready to work on.

**Comment by jamiealbrecht** [comment]
Working on this now! Also, @ericronne, there are graphs in these pages that will eventually need you. :) <3

**Comment by jamiealbrecht** [comment]
Now on the how-it-works branch @coreycaitlin and @brentryanjohnson. I left out economic impact, costs, laws and regulations based on what we did with other additions. I have some questions about how to manage the revenue part.  

I just realized that this is working off the old site, but I guess that's okay for the moment.

**Comment by coreycaitlin** [comment]
After discussing, the central goals of this page should be:

- Help users understand roughly who governs forests on federal land
- Give users just enough context to figure out how to dive deeper
- Link to any relevant content within the site (there might not be any)
- Provide a few rich pathways for users to explore if they want to learn more about this topic

We should also avoid the following:

- Duplicating data owned by other agencies
- Hard-coding data into the content that will need to be manually checked/maintained each year
- Duplicating process explanations that exist on other agencies' sites (esp. if those are the agencies that own those processes)

**Comment by jamiealbrecht** [comment]
Hello! I made a number of changes since we last talked.

- Updated headings to make it easier to scan
- Added links so that users can dive deeper into each section 
- Linked to relevant content (U.S Forest Service and BLM) where applicable. There's likely a good spot to link to the tribal addition, @coreycaitlin when that is ready. 

I think this is definitely getting there. The main section I am most concerned about is revenue. It was hard to know how deep to get into explaining the various revenue streams and how they are distributed into different funds. I could use some other brains and eyes on that section. 

With <3
jamie

**Comment by coreycaitlin** [comment]
I think we can close this out with #2356. Thank you @jamiealbrecht!
