### ISSUE TITLE
Chart line rounding redux

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2320]
On the Alaska jobs-by-commodity section, @mentastc pointed out that some of the y-axis markers (the light gray dotted line above the bars) are confusing. For instance, this one should probably be labelled `$15K`, not `$20K`:

![screen shot 2017-06-29 at 4 50 35 pm](https://user-images.githubusercontent.com/1450354/27715283-fe882b0e-5cea-11e7-9f39-b236cd7601e9.png)

It's probably time to tweak this rounding algorithm again (see #2119 for history).

**Comment by gemfarmer** [comment]
@coreycaitlin Oi. Yeah that's not great. If I remember correctly we are currently:

1. rounding to 1 significant figure by default
2. If the value provided is smaller than any of the year values, up to 2 sig figs
3. So on and so forth until all the values are higher

I think instead of only checking to see if the values are higher, we could also make sure that the margin of difference isn't too small or too great. 

Upside: accuracy
Downside: we will likely end up with some pretty obscure values (which I think is what we were trying to prevent against in the first place.

**Comment by coreycaitlin** [comment]
I think #2321 is a solid improvement that deals with some of the more misleading rounding issues. Closing this issue; we can open a new one if we decide to re-visit the general scaling/rounding question sitewide.
