### ISSUE TITLE
Content: Renewables addition

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2333]
[Draft content here (limited access)](https://drive.google.com/drive/folders/0B-tWFsKyyEsKX3BST0VYMjdCa1E)

**Comment by jamiealbrecht** [comment]
This content is now final. It's [here](https://drive.google.com/drive/u/1/folders/0B-tWFsKyyEsKX3BST0VYMjdCa1E) (limited access).

**Comment by brentryanjohnson** [comment]
In order to begin integrating content from [DOI/energy](https://www.doi.gov/energy), can we add language related to the role of [Bureau of Reclamation](https://www.usbr.gov/main/about/) and link there?

**Comment by jamiealbrecht** [comment]
Thanks for the help, Corey and RJ!

I made a few changes:
1. I added a few links to state pages so we can call out top producers in each section. I didn't do that for biomass because it's California (again). 
2. I quickly added some information about the Bureau of Reclamation. Feel free to edit that, RJ! I am sure you know more about that than I do. 

Let me know what you think!

**Comment by coreycaitlin** [comment]
Thank you @jamiealbrecht — closing with #2356
