### ISSUE TITLE
Automate link checking?

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#2375]
Broken links are an ongoing, niggling issue with the site.

Is there a technical, automated way to check links, so we don't have to rely on randomly tripping over them?

cc @toolness

**Comment by toolness** [comment]
Yep, there is definitely a way to do this! I've added automated _internal_ link checking to a bunch of sites at 18F, but they don't check outbound links simply because e.g.:

* we didn't want e.g. sites that might _temporarily_ be down to trigger false build failures.
* we didn't want CircleCI to take a really long time to check all the outbound links on the site.

so while there are potentially some downsides to doing the external link checking on every single GitHub PR, it might be good to at least add a script that allows the external links to be checked when run manually.

**Comment by ericronne** [comment]
Thanks!

@coreycaitlin and @winzenburg, in favor of `ad[ding] a script that allows the external links to be checked when run manually`, to at least lessen the burden?

**Comment by coreycaitlin** [comment]
This would be really helpful to have, either as a standalone script OR as a CI tool that could run only for pushes to `staging` and `master`.

**Comment by jennmalcolm** [comment]
This will be covered through manual content audits, so we're closing this.
