### ISSUE TITLE
Workshop synth: product vision next steps

### ISSUE THREAD

**Issue by winzenburg** [18F/doi-extractives-data#2470]
As the design innovation team, I want to define the next activities to be done, so we can clearly define the product vision

**Comment by alexpandel** [comment]
I'm gonna close this one, since I think we aligned on the next step being us having a follow-up product vision session starting with me leading the group through a session this week touching on how 18F thinks about product framing and vision, and shooting to get us to at least a v1 of our product vision for the NRRD site.
