### ISSUE TITLE
Subheading hierarchy visually confusing

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2487]
On account of their relative size, our h3s and h4s visually convey the reverse of their hierarchical relationship when presented next to each other (h4 is larger than h3). Can we tweak the styling so h4s are (visually) hierarchically inferior to h3s?

![headings](https://user-images.githubusercontent.com/32855580/33405711-534f9ff4-d51e-11e7-8785-d3a265ba75ff.PNG)

**Comment by ericronne** [comment]
#greatminds

that adjustment was a part of the changes i made in my [typography normalizing branch](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/typography-normalizing-1/), yet to be merged

**Comment by brentryanjohnson** [comment]
Hey @ericronne !

It looks like we merged the typography normalizing branch, but I don't see a change in the h3-h4 styling. Some changes on this page didn't merge properly into master (some links weren't updated), so I wonder if it might be related to that?

![image](https://user-images.githubusercontent.com/32855580/33788791-ff68b1e8-dc28-11e7-93c5-907b8c1bfb14.png)

**Comment by ericronne** [comment]
👀

**Comment by ericronne** [comment]
Okay, turns out there's a bit of a gordian knot going on. The main issue all along was markdown + style overrides.

- "Plan" here is strong in the [markdown file](https://raw.githubusercontent.com/18F/doi-extractives-data/dev/_how-it-works/tribal-production.md), rather than an h4 …

![image](https://user-images.githubusercontent.com/9259185/33843061-eb7b6f96-de61-11e7-9f36-f4fd368377b4.png)

- And on top of that, default h3 header sizing is overridden in [_content.scss](https://github.com/18F/doi-extractives-data/blob/dev/_sass/blocks/jekyll-layouts/_content.scss), which throws off the structure.

I'm onnit …

**Comment by brentryanjohnson** [comment]
@ericronne For the screenshot above, I replaced the <p> and <strong> tags with <h4> in the browser.

**Comment by ericronne** [comment]
H3 override was throwing it off. PR imminent.
