### ISSUE TITLE
Research: Synthesize what we learned

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2535]
Let's make sense of what we learned from #2476 and identify how we'll use this info to move the product forward!

This issue is done when the following have occurred:
- [x] group synthesis session scheduled (for Tues 12/19)
- [x] all researchers (Chris, RJ, RW, Kim & Alex) meet for group synthesis
- [x] a brief research summary is added to [this folder](https://github.com/18F/doi-extractives-data/tree/research/research/15_cheeseycheetah) in the research branch
- [x] a new issue is created for next steps identified during synthesis

**Comment by alexpandel** [comment]
FYI, I'm being a goober and starting my draft in [a Google doc here](https://docs.google.com/document/d/17j1lcfViQQGvS4iXBOHzK0RPSLAVrstvf8HQFMa0AYY/edit#) so I can make mental notes to myself more easily while I'm in process, but I plan to transfer this into a PR on Github for review once I have a first draft ready for some other :eyes:!

**Comment by alexpandel** [comment]
I didn't get as far as I would have liked on this, so I'm actually gonna leave it in [the google doc](https://docs.google.com/document/d/17j1lcfViQQGvS4iXBOHzK0RPSLAVrstvf8HQFMa0AYY/edit#) vs transferring it to Github since it's still rough enough that it might be easier for y'all to collaborate on in the doc itself. Got a very rough narrative flow mapped out, with some placeholders for specific examples from the Mural/notes if needed.

**Comment by alexpandel** [comment]
This is now done, and posted [here](https://github.com/18F/doi-extractives-data/blob/research/research/15_cheeseycheetah/research_results.md)! 🎉
