### ISSUE TITLE
Create custom analytics reports

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2546]
Creating/implementing  a measurement plan for revenuedata.gov
to generate reoccurring reports for Jennifer Malcolm and Ryan Johnson
so they can get better insights into user behavior on the NRDD website

Reports Include:
-Audience
-Location
-New vs Returning
-Technology 
-Device
-Acquisition
-Top Pages
-Top Sections
-Landing Pages
-Top Downloads

**Comment by winzenburg** [comment]
Working with Ryan Johnson to define the measurement plan

**Comment by winzenburg** [comment]
Created the monthly reports to be send to @jennmalcolm and @brentryanjohnson . Also documented the reports on the Github research wiki https://github.com/18F/doi-extractives-data/blob/research/research/16_ReflectingReindeer/measurement-plan.md

**Comment by jennmalcolm** [comment]
Thank you!

Sent from my iPhone

On Dec 21, 2017, at 4:03 PM, Ryan Winzenburg <notifications@github.com>
wrote:

Created the monthly reports to be send to @jennmalcolm
<https://github.com/jennmalcolm> and @brentryanjohnson
<https://github.com/brentryanjohnson> . Also documented the reports on the
Github research wiki
https://github.com/18F/doi-extractives-data/blob/research/research/16_ReflectingReindeer/measurement-plan.md

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/18F/doi-extractives-data/issues/2546#issuecomment-353457046>,
or mute the thread
