### ISSUE TITLE
State disbursements and revenue data: funds with value of zero show sliver of charted value

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/doi-extractives-data#2575]
A bug is causing horizontal bars with a value of zero to show a fraction of value.

This doesn't appear to be a problem with national data, but it occurring with Wyoming state data in the [state disbursements](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/update_optin_state_data/explore/WY/#state-disbursements) section.

![image](https://user-images.githubusercontent.com/32855580/34545958-89dcc20c-f0a5-11e7-8b7a-339eb787e49d.png)

**Comment by coreycaitlin** [comment]
It looks like this issue is confined to the [WY opt-in disbursements chart](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/update_optin_state_data/explore/WY/#state-disbursements). This looks like it's actually a bug with duplicate funds in WY.

Zero values are represented correctly in the [federal revenue charts](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/update_optin_state_data/explore/WY/#federal-revenue).

**Comment by brentryanjohnson** [comment]
This issue is also happening with [Montana state revenue data](https://revenuedata.doi.gov/explore/MT/#state-local-revenue).

![zero values in montana chart](https://user-images.githubusercontent.com/32855580/36453801-48990b2e-164e-11e8-8674-3465c0202274.png)
