### ISSUE TITLE
Wiki: Update sitemap and IA documentation

### ISSUE THREAD

**Issue by coreycaitlin** [18F/doi-extractives-data#2621]
The wiki should have current (as of Feb 2018) documentation of the site structure, content age, and content sources.

**Comment by coreycaitlin** [comment]
[Started here](https://github.com/18F/doi-extractives-data/wiki/Information-architecture)

**Comment by brentryanjohnson** [comment]
This is great! Just a few questions/observations:

- The primary audience for this seems to be internal, but it still might be useful to spell out the acronyms for "IA" and "EITI" somewhere.

- Why is Illinois described as a "priority state"? Is there an appropriate context here to define what "priority" and "opt-in"states are? 

- At least 6 links in the [Initial IA notes (December 2015)](https://github.com/18F/doi-extractives-data/wiki/Sitemap#initial-ia-notes-december-2015) section are broken. I'm torn between keeping it as an archive and removing it because it doesn't structurally represent the sitemap anymore. What do you think @coreycaitlin?

Thank you for documenting this!

**Comment by coreycaitlin** [comment]
@brentryanjohnson This is definitely an internal/working document — the primary audience is you! I'm happy to define IA and EITI if helpful, but they're both defined on the site itself (in the glossary and about page, I think). [Priority](https://revenuedata.doi.gov/how-it-works/state-laws-and-regulations/) and opt-in states are explained in the site (albeit deep in the content), and both are artifacts of the EITI/MSG process...happy to explain more, if it will help you make decisions about that content!

Links in the old IA notes are likely broken because we've restructured pretty fully since then (I didn't touch that section at all). If you think it's useful, we should keep it — if it feels like clutter, let's remove. This is a document for helping you move forward and make decisions, so it's your call!

**Comment by brentryanjohnson** [comment]
All sounds great @coreycaitlin. Thank you!
