### ISSUE TITLE
Add contact email for Data Display Team

### ISSUE THREAD

**Issue by jennmalcolm** [18F/doi-extractives-data#2660]
Now that we have Data Retrieval's contact info available on the downloads pages, that will help us track data request issues and ensure we're not missing any important data on the site. For those who never go to the downloads page, there is no easy way to contact us. We want emails related to the site content to come to the Data Display group rather than the Data Retrieval group like the link on the downloads page. This could also be a way to collect additional user feedback and experience information. So, I propose we add a "contact us" link in a more obvious place that can be seen on pages besides the downloads. It would go to a new Data Display/NRRD email. One suggestion from Nathan is to include a link next to the Glossary and Downloads links. This is one potential option which would make it easy to contact Data Display from any place on the site, but that might be confusing on the downloads pages since we would show two contact links to different emails. So, we can explore other options too.

![image](https://user-images.githubusercontent.com/30806839/36169163-74ada5ce-10c9-11e8-8c99-798275a4323d.png)

Steps to work this issue

- [x] Decide what new email address (DataDisplay or NRRD@onrr.gov or ???) we want to use
- [x] Contact Help Desk for email creation
- [ ] Discuss Options for where/how to add contact link on NRRD
- [ ] Usability testing (?)
- [ ] Implement changes on NRRD

**Comment by brentryanjohnson** [comment]
I like this idea! We already have some "main" contact information in the footer of the site, currently limited to the postal address. 

I created a [contact file](https://github.com/18F/doi-extractives-data/blob/dev/_data/contact.yml) in the `_data` directory in which we can update contact information in one place and plug in variables where we want that contact information to appear. I haven't (yet) reformatted the footer to reference these variables, so perhaps we can scope that work with this issue.

It makes sense to me to add the email address (once created) to the footer with the existing contact information, but I'm happy to discuss alternatives!

**Comment by brentryanjohnson** [comment]
I've created a branch and added the new IDM email address to the footer, where the mail address currently resides.

![footer contact](https://user-images.githubusercontent.com/32855580/36866429-1ed2983c-1d47-11e8-9a8a-5e60a807a760.png)

Obviously we need to change the link color in order for this to be visible and 508-compliant. @master12 Do you mind looking through the style sheet for an existing link class that might provide the contrast we need for this to pop out on a dark background? If there isn't one, we may need to create a new class.

I thought we could start by adding the email here in the footer, because we already have contact information there and it's a common convention for footers. But we can certainly revisit the location and see if we need to move/add the email address elsewhere.

**Comment by brentryanjohnson** [comment]
Also, I've converted the footer contact information to variables, so we can change them in the `_data/contact.yml` file, and the content will change across the site.

``` 
          Office of Natural Resources Revenue, {{ site.data.contact.information_data_management.name }}<br>
          {{ site.data.contact.information_data_management.street }}, {{ site.data.contact.information_data_management.city }} {{ site.data.contact.information_data_management.zip }}<br>
          <a href="mailto:{{ site.data.contact.information_data_management.email }}">{{ site.data.contact.information_data_management.email }}</a>
```

**Comment by brentryanjohnson** [comment]
@master12 Just getting back around to this. It looks like the nearby `link-active-beta` class will work for us. I'll add it shortly and push it up to a PR.
