### ISSUE TITLE
Add transition goals & product training materials to wiki

### ISSUE THREAD

**Issue by alexpandel** [18F/doi-extractives-data#2681]
Let's get some of our higher-level project docs that are likely to be useful on an ongoing basis out of Google Docs and into the wiki!

This is done when:

- [x] we've added the transition goals to the wiki
- [x] we've added the product training materials to the wiki

**Comment by jenniferthibault** [comment]
@alexpandel let's put our brains together on this! If you can point me to the product training docs, it sounds like there might be some overlap with the onboarding materials I'm about to add to the wiki in #2744

**Comment by alexpandel** [comment]
I've got a rough draft for this (and for where it will go in the wiki) [here](https://docs.google.com/document/d/1BGKRQVcSgXhw3uNHwdVNNduY-6uIZNEAyHYsmDsvhcw/edit?pli=1). Trying to figure out the best/least clunky way to get the slide decks into the repo — checking to see if we have approval to use SlideShare tomorrow when I'm in the office (apparently I have to be on the GSA network to use the site that allows me to check 🙃)

**Comment by alexpandel** [comment]
I tackled adding the transition goals to the wiki today, which I added to the Archive section [here](https://github.com/18F/doi-extractives-data/wiki/Transition-goals). In doing so, I also:

- added years to the pages in the Archive section to make it easier to quickly scan those for relevance from the sidebar navigation
- renamed the "User research" section in the sidebar navigation to "Design & user research"
- moved "[Little rules for designing with data](https://github.com/18F/doi-extractives-data/wiki/Little-rules-for-designing-with-data)" out of the Archive section and into the "Design & user research" section, since this feels like evergreen content that will be useful in future design work as well

Please let me know if any of this feels wrong to any of you though, and I can absolutely adjust!

**Comment by alexpandel** [comment]
Ok, unless we hear otherwise from @jennmalcolm about our ability to use SlideShare for the product management training decks, I'm currently planning on just uploading them as PDFs to a folder somewhere in the repo, and linking them to a page in the wiki that I'll add about the training work.
  
@brentryanjohnson, as our resident content guru, do you have thoughts on where would be the best, least disruptive place to add a folder to the repo? If I make a top-level one will that mess anything up when the site builds?

**Comment by brentryanjohnson** [comment]
I'm not sure about this one, @alexpandel. I don't particularly want to add a new folder in the main repo for these docs, because it will be difficult to distinguish the codebase and site documents from support documents. We would probably need to add the directory to the `ignore` files so it doesn't try to build.

Branching seems like it could be an option, but the research branch has proved somewhat awkward for both contributing (pulling a down the branch locally) and semantics (the sprint names are esoteric for folder structures).

Two questions:
- Is it possible to share the Google docs and link to them from the Wiki? (I realize this issue is about moving them out of Google docs, but if it's possible for folks to access them there, it might be the best option)
- What are your thoughts on a "transition branch" similar to the research branch? It seems like overkill for a temporary file store, but that may be the best option if there are several docs.

**Comment by alexpandel** [comment]
Hmm, yeah, all good thoughts. Just keeping them in Google Docs and sharing them that way would have been my first choice, but GSA won't let us make them publicly viewable :( 

I think the branching option may be our best bet, though I agree it's not ideal. Blergh. I'll start there and we can adjust if we come up with another solution!

**Comment by jennmalcolm** [comment]
Yep, @alexpandel, they look a bit blurry to me too.

We're almost there!
