### ISSUE TITLE
Pair to Define Toggle Control

### ISSUE THREAD

**Issue by mcharg** [18F/doi-extractives-data#2889]
This will be a test for processes for creating new visual design.

**Comment by mcharg** [comment]
@jenniferthibault Now that we've defined what the toggle should look like, what's the next step to getting it in the style guide?

**Comment by jenniferthibault** [comment]
Next steps would be to:
1. Capture the design in this github issue to document for the rest of the team where we landed on the first draft, and get the chance for quick feedback, if there is any at this point. Capture:
   - parameters that informed our design choices  
   - examples of default styles   
   - examples of interaction states  
   - examples of responsive state changes  

2. Create a new issue for building the component in code. Completion criteria might include:
   - building the master CSS/HTML style classes
   - applying them in mockups or prototypes (if ready)
   - adding component to the style guide (this could theoretically be separate, but I like to do it all in one to make it part of the regular process)

I often find that it's helpful to have whoever styled the thing pair with whoever is building the thing in code to look at an example of the component when they're nearing a first draft, but before filing a pull request. This helps make sure you're both on the same page, and is a good chance to make sure everything looks and works like you expected it to early on.

3. Create another new issue for writing notes and documentation for how this component is used that will fill in the style guide notes tab.
   - Optionally, this could be included in the first or second issue, but I find it's helpful to separate content tasks from code-based implementation tasks. And often, the team members capable/responsible for each will be different people. It's likely that the notes/documentation content for a component might need slight updates over time as the component is used in more places, and you have a firmer understanding of the site's guidelines.

____

This is how I've done it before, but of course you all will find what works for you.

@mcharg are you up for updating this issue with the items from step 1? I'd also be glad to give it a first pass if you'd rather see an example first.

**Comment by mcharg** [comment]
@jenniferthibault Yes, I can do #1.

**Comment by mcharg** [comment]
Parameters that informed the design choices:

- Match to existing patterns
- Match to known use cases
- Used styling to go with secondary and tertiary buttons

See attached images for default state.

![toggledesktop](https://user-images.githubusercontent.com/38465926/40797003-c97884c0-64d4-11e8-8c81-a4d13933eb6f.PNG)
![togglemobile](https://user-images.githubusercontent.com/38465926/40797004-c98d1ade-64d4-11e8-9f67-e93684835789.PNG)

Prototype for interactivity:
Desktop: https://ofxchl.axshare.com/#g=1&p=toggle&view=default
Mobile: https://ofxchl.axshare.com/#g=1&p=toggle&view=a

Specifications:
- 5 px corner radius on the left and right (or top and bottom on mobile) buttons.
- 0 px corner radius on center buttons.
- Selected button color and font match the styling for tertiary buttons.
- Unselected button color and font match the styling for secondary buttons.
- When the screen gets narrow enough that all the options won't fit on the screen without horizontal scrolling, they switch to the mobile display with stacked buttons.
- When stacked on mobile, the pixel height increases to 40px per button and the width of the screen minus margins.
- If there are any toggles on the same page as one that has switched to the mobile view, but still fit together on one row, the buttons should increase to 40px high, but should stay on the same row.

**Comment by jenniferthibault** [comment]
@mcharg this is great, especially how you're showing interaction prototypes and referencing other patterns that set the styles for this one. One way to make that stronger would be to link references to those patterns to their pages in the style guide.
For example: 
- Selected button color and font match the styling for [tertiary buttons
](https://revenuedata.doi.gov/styleguide/components/detail/buttons.html)


The only parameter I'd add is that we also need this toggle to accept icons as the content, instead of text in some instances. I'd add that to the list with an example prototype or screenshot.

@master12 as the receiver and user of these notes, is there any info missing or anything you'd do differently?

**Comment by mcharg** [comment]
Created #2911 to address step 2 above.

**Comment by mcharg** [comment]
Created #2918 to address step 3 above.

**Comment by mcharg** [comment]
@master12 Do you have any feedback on the specifications?

**Comment by master12** [comment]
A couple questions:
1. Is there a max width or min width?
2. For mobile we may want to set a breakpoint for screen width
3. If we use text do the buttons wrap if they stretch to far? Or we switch to mobile?
4. If we set max width what happens to the text inside the button? Wrap? Clipped?

Thats what I have so far.

**Comment by master12** [comment]
I will check what the breakpoint is we use now and go with that. There are general guidelines so I assume we are using that.

**Comment by jenniferthibault** [comment]
Your breakpoints are defined in the .scss here: https://github.com/18F/doi-extractives-data/blob/dev/_sass/_grid.scss#L8

```
// Breakpoints
$tiny: em(480);
$small: em(600);
$medium: em(768);
$large: em(900);
$huge: em(960);
$huge-plus: $huge + em($max-vw-margins);
$jumbo: em(1500);
$massive: em(1800);
```

**Comment by mcharg** [comment]
@jenniferthibault Is there a rough translation for how many pixels = an em?

**Comment by jenniferthibault** [comment]
@mcharg to answer your question, I've been digging myself into a rabbit hole on this and could use some help from @mentastc . In the expressions copied above, does `em(480)` = `480em`?

Sharing my reading list:
- [All your base, are belong to us — or what base size do em-based media queries use?](http://blog.w3conversions.com/2015/03/all-your-base-are-belong-to-us-%E2%80%94-or-what-base-size-do-em-based-media-queries-use/) by Stephanie Rewis, March 2015
  - This has the answer to your direct question, that in this case, *since it's a media query*, 1em=16px _unless the user has permanently overridden those settings in their browser_ But in other scenarios, 1em can = other px dimensions. So layout changes are determined by the line length, not the number of pixels. 
  - This is also what makes me suspect that the two expressions above (`em(480)` and `480em`) are not exactly the same
- [REM vs EM – The Great Debate](https://zellwk.com/blog/rem-vs-em/) Zell Liew, Feb 2016
- [PX, EM or REM Media Queries?](https://zellwk.com/blog/media-query-units/) Zell Liew, March 2016

**Comment by brentryanjohnson** [comment]
@jenniferthibault and @mcharg I believe you're looking at [Sass `em()` function](https://css-tricks.com/snippets/sass/px-to-em-functions/#article-header-id-0) declarations that accept pixel values and convert them to `em`s in the CSS output.

The values you see in the [Sass file](https://github.com/18F/doi-extractives-data/blob/dev/_sass/_grid.scss#L8) should be pixel values. I checked this out and found an obvious breakpoint at `768 px`, which is declared as a breakpoint in the stylesheet.

![breakpoint](https://user-images.githubusercontent.com/32855580/40944233-dc8acf8c-6808-11e8-9bd4-70d406e53297.gif)

**Comment by mcharg** [comment]
I updated the specs to reflect the 768 px breakpoint.
