### ISSUE TITLE
Main nav styling

### ISSUE THREAD

**Issue by ericronne** [18F/doi-extractives-data#697]
Lmk if any details are missing here ...

![image](https://cloud.githubusercontent.com/assets/9259185/10897793/0e9e9cf0-818a-11e5-9c8e-14c8272f87fd.png)
![image](https://cloud.githubusercontent.com/assets/9259185/10897803/1a398764-818a-11e5-8534-9522c7f8c317.png)

**Comment by meiqimichelle** [comment]
@ericronne Are we doing a drop-down? I'm generally nervous about drop-downs that also let you click on the heading -- one or the other is better. ie, is Explore Data a subpage, or is it only a link that reveals the drop-down? I vote for link-to-subpage.

**Comment by ericronne** [comment]
In this design, the heading would also be a link (following fec paradigm), to the landing page for that section (eg Explore Data). Don't want to make you nervous! We could add "Main" (eg) to the top of that list. Thoughts, @nicoleslaw?

**Comment by nicoleslaw** [comment]
Hrmm, what would be under "main" or the Explore tab? Is it this view? https://federalist.18f.gov/preview/18F/doi-extractives-data/bh-diving-graphics/resources/#all/revenue/US

**Comment by gemfarmer** [comment]
I'm not sure what 'main' would be. As far as I know we don't have an Explore Data landing view. Or do we? If not, it would be confusing to have 'main' and 'Federal Revenue' go to the same page. 

If Explore Data is a dropdown in the nav, but also exists as a link/button in the landing intro section, that is confusing.

Maybe the solution is to create a 'main' view and treat the Explore Data as a link to that view?? Thoughts?

**Comment by nicoleslaw** [comment]
Wondering if it might be useful to cluster the sets together visually so less-familiar readers can understand? Here's one take on that which could be the main landing page in a way:

## Explore the Data

### Production
- All lands and waters
- Federal lands and waters

### Revenue
- Federal revenue
- Corporate revenue
- Disbursements
- Exports

### Economic impact
- Gross Domestic Product
- Jobs
  - Wages and salaries
  - Self-employment

**Comment by meiqimichelle** [comment]
It is this: https://github.com/18F/doi-extractives-data/issues/655

**Comment by meiqimichelle** [comment]
Oh, and the visual design task for this is here: #688. (forgot that in the last issue)

To recap: all of those global navigation links have landing pages for consistency, and because we thought they needed them. For example, the explore data landing page will mirror content that will be on the homepage 'explore data' focus section (....speaking of, @shawnbot should we do that wireframe next?)

Re: drop-down usability: If there are no landing pages, then drop-downs can work. Still, drop-down usability is risky and need lots of testing. The 'click here for drop-down, click again for a landing page' does not test well, and I'm not keen on adding a 'main' link that is a different level of hierarchy to the drop-down itself.

**Comment by ericronne** [comment]
quick hangout mayhaps?

**Comment by ericronne** [comment]
Ok let's kill drop-downs for now, provided visitors sufficiently grok the contents of each section :)

@gemfarmer, revised....
![image](https://cloud.githubusercontent.com/assets/9259185/10915168/2f65f4f6-821b-11e5-996d-087141096fd5.png)

**Comment by gemfarmer** [comment]
:+1:

**Comment by ericronne** [comment]
[eiti style guide WIP.sketch | uploaded via ZenHub](https://files.zenhub.io/563a5f2aac62821e1792dfde)
