### ISSUE TITLE
Visual design: footer

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#742]

**Comment by ericronne** [comment]
Associated wires issue: #692

**Comment by ericronne** [comment]
Here's a layout for discussion! Lots going on here, but hopefully presented in a semi-clear / logical / usable format. 
 - I gave lots of love to the ethnio link, because i think we want a lot of participation here (valid assuption?)
 - To me it seemed odd to only call out the subs for two sections, so i added subs for explore data (the only other section with subs).
 - "See our work" seems like it could apply to the site data, or any number of things. So i made it more direct. Again, let's discuss!

![footer - eric reco](https://cloud.githubusercontent.com/assets/9259185/11280178/47260b34-8eba-11e5-8007-d31c0beae21b.png)

**Comment by gemfarmer** [comment]
@ericronne I'm going to get going on this. Do we have a white version of the EITI logo?

**Comment by meiqimichelle** [comment]
Also @gemfarmer one edit for the moment to Eric's mock as you're coding -- take out the 'Department of the Interior's' in the contact line. Should be 'Contact the USEITI Secretariat' straight-up. Thank you!

**Comment by ericronne** [comment]
White logo (svg)
https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaMjdkdlV3YXRuSnM/view?usp=sharing

**Also** it looks like we're using an old, non-508-compliant, version of the logo throughout the site. Here's the correct one...
https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaSG1TS2xNVDNuTzQ/view?usp=sharing

**Comment by gemfarmer** [comment]
@meiqimichelle @ericronne for US Natural Resources, where should I point people? `how-it-works/natural-resources/production/`?

For economic impact: `/explore/exports/`?

**Comment by meiqimichelle** [comment]
@gemfarmer can we do a like `how-it-works/natural-resources/#production/`section jump for now? (not sure I url'd that correctly, but perhaps you get the idea).

Each of those are meant to call out the sections on the page indicated above them.

**Comment by gemfarmer** [comment]
@meiqimichelle that makes more sense than what I was going to do :smile:

**Comment by meiqimichelle** [comment]
@gemfarmer Please close this issue when you're OK with the visual design (questions answered, etc)
