### ISSUE TITLE
Content: Update What's New page

### ISSUE THREAD

**Issue by nicoleslaw** [18F/doi-extractives-data#792]
Add a summary of updates to `about/new/`
~~- [ ] MSG recommendations (p. 13-14; 91-94, Exec Summary)~~
- [x] Data sets being added
- [x] Plans for the website, etc.

**Comment by nicoleslaw** [comment]
Per Isabelle, we will exclude the recommendations sections (p. 13-14; 91-94) as they are more relevant to people reading the Executive Summary

**Comment by nicoleslaw** [comment]
@coreycaitlin This task can wait for a bit until the other content is finalized. Assigning to you as backlog in the meantime.

**Comment by coreycaitlin** [comment]
First pass [here](https://github.com/18F/doi-extractives-data/commit/7d5975fdf3e23e7152d8465747fdc152bf3ee348).

@Isabelle1512, could you take a look and let me know if this is accurate? (I attempted to summarize some of what we talked about, but may have missed/confused something.)

@meiqimichelle — anything big missing here? (Esp. data sets being added)

**Comment by Isabelle1512** [comment]
@coreycaitlin : looking great, captured the opt-in stuff beautifully, and I'm sure Michelle will have feedback too. Two tiny things: "U.S. energy resources and policy" - the effort is also for nonenergy minerals...better to say something like natural resource management (or policy...). Also "natural resource industry" - may want to just say extractive industries.

**Comment by meiqimichelle** [comment]
Yep, looks good! As for data stuff:

- Production data: needs to be clear that it is data from production on federal lands (because there's another dataset that is not new with data from production on all lands)
- Another new one is the "federal revenue by company" dataset. This is info on the revenue received by the government from production on federal lands, sorted by company who paid the revenue. It is also produced by ONRR.

As the looking forward to section, we could add:
- Making the reconcilliation data interactive
- Listening to people in the community/user feedback/other nice way to say this with link to our feedback form.

**Comment by coreycaitlin** [comment]
Edited! I also fixed the layout.

This page still feels very long — @meiqimichelle what do you think about cutting the "Here's how we've made it more useful" list and going straight to new info? I'm not sure that top list is adding a ton of value here.

What's the link for the feedback form? Do we have that yet?
