### ISSUE TITLE
Turn on font ligatures for all headings

### ISSUE THREAD

**Issue by meiqimichelle** [18F/doi-extractives-data#830]
We're not getting lovely ligatures on the site. They should be turned on for all headings.

We have:
![screenshot 2015-11-19 18 28 40](https://cloud.githubusercontent.com/assets/4827522/11289567/61e61744-8eeb-11e5-9ab4-55ff2a0fa7c2.png)

We want:
![screenshot 2015-11-19 18 28 31](https://cloud.githubusercontent.com/assets/4827522/11289569/632289bc-8eeb-11e5-8138-6e24e931011c.png)

**Comment by dmsnell** [comment]
@meiqimichelle I'm not sure that this is a styling problem as much as it is a font problem. It appears that the **Lato** font in use is missing the `ff` ligature. Turns out that Lato has some real criticism all-around for the `fi` ligature as well, since the ascender of the `f` doesn't reach over the `i` but the dot is still missing.

Here is where I was experimenting on [Typecast](http://typecast.com/preview/google/Lato) to test where I knew the font should have all pieces active.
<img width="740" alt="screen shot 2016-07-30 at 9 27 27 pm" src="https://cloud.githubusercontent.com/assets/5431237/17274583/e159b8c2-569c-11e6-81b0-4e076a2b9d1b.png">

Basically this means that I don't think it's possible to get the `ff` ligatures unless a new font is considered. It's possible to replace `ff` with the Unicode glyph `ﬀ`, but it won't look nice.

<img width="274" alt="screen shot 2016-07-30 at 9 27 51 pm" src="https://cloud.githubusercontent.com/assets/5431237/17274589/1ba32d38-569d-11e6-8d1e-c379f18010f8.png">
I believe that it looks heavier than the surrounding text when replaced like this.

For comparison, here we have `O + ﬀ + ffi`
<img width="292" alt="screen shot 2016-07-30 at 9 33 33 pm" src="https://cloud.githubusercontent.com/assets/5431237/17274593/57e3e0d0-569d-11e6-8880-354655c8b792.png">

**Summary**
 - Ligatures are _already on_
 - _Lato_ doesn't have a ligature for `ff`
 - Pick a new font or deal with it

:smile:

> Testing performed on [offshore oil & gas page](http://localhost:4000/how-it-works/offshore-oil-gas/)

**Comment by meiqimichelle** [comment]
It seems like this is working now. I'm not sure why, but I'm going to go with it:

![screenshot 2016-09-06 13 52 37](https://cloud.githubusercontent.com/assets/4827522/18290673/4cabae50-7439-11e6-885c-116d25ace178.png)

![screenshot 2016-09-06 13 54 11](https://cloud.githubusercontent.com/assets/4827522/18290699/682e4462-7439-11e6-8877-89103b7f1911.png)
